#! /usr/bin/env python3
import message_filters
import sys
sys.path.append('../')

import rospy
from nav_msgs.msg import Odometry
from slave_msgs.msg import robot_state
from nlink.msg import node_frame2
from geometry_msgs.msg import Pose
from geometry_msgs.msg import Twist
from gazebo_msgs.msg import ModelState
from ekf_localization import ekf_odom_uwb
import numpy as np
from math import sin, cos, atan2, asin


# robot state: x, y, theta  (theta in robot_ekf_state.pose.pose.position.z)

pub_robot_state = rospy.Publisher('robot_state', robot_state, queue_size=10)
seq = 0
robot_name = "agent1"
list_info_sub = []
init = False

mut_1 = np.array([[0], [0], [0]])

sigmat_1 = np.ones((3, 3))
sampletime = 0.05
sigmaQ = np.array([[0.05, 0], [0, 0.05]])
alpha =  [0.05, 0.05, 0.05, 0.05, 0.05, 0.05]

def quarter2angle(x, y, z, w):
    r = atan2(2*(w*x+y*z),1-2*(x*x+y*y))
    p = asin(2*(w*y-z*x))
    y = atan2(2*(w*z+x*y),1-2*(z*z+y*y))

    return r, p, y

def angle2quarter(angle_x, angle_y, angle_z):

    w = cos(angle_x/2) * cos(angle_y/2) * cos(angle_z/2) + sin(angle_x/2) * sin(angle_y/2) * sin(angle_z/2)
    x = sin(angle_x/2) * cos(angle_y/2) * cos(angle_z/2) - cos(angle_x/2) * sin(angle_y/2) * sin(angle_z/2)
    y = cos(angle_x/2) * sin(angle_y/2) * cos(angle_z/2) + sin(angle_x/2) * cos(angle_y/2) * sin(angle_z/2)
    z = cos(angle_x/2) * cos(angle_y/2) * sin(angle_z/2) - sin(angle_x/2) * sin(angle_y/2) * cos(angle_z/2)
    
    return x, y, z, w

def robot_msg_callback(*args):
    #  args[0] -- uwb
    #  args[1] -- odom   

    model_state = ModelState()
    robot_state_msg = robot_state()

    global seq, mut_1, sigmat_1, init

    # global num_robot
    seq += 1
   
    # header
    robot_state_msg.header.stamp = rospy.Time.now()
    robot_state_msg.header.seq = seq
    robot_state_msg.header.frame_id = "global"

    # name
    model_state.model_name = robot_name

    # model pose ekf fusion from uwb and odom 

    ut = np.array([[args[1].twist.twist.linear.x], [args[1].twist.twist.angular.z]])
    zt = np.array([[args[0].position.x], [args[0].position.y]])
    
    # init
    if not init:
        mut_1[0, 0] = zt[0, 0]
        mut_1[1, 0] = zt[1, 0]
        init = True
        
    mu_t, sigma_t = ekf_odom_uwb(mut_1, sigmat_1, ut, zt, alpha, sigmaQ, sampletime)
    
    var_range = np.sqrt( (mut_1[0, 0] - mu_t[0, 0]) ** 2 + (mut_1[1, 0] - mu_t[1, 0]) ** 2  )
    print('range:',  var_range)
    if var_range > 0.1:
        mu_t[:] = mut_1[:]

    pose = Pose()

    pose.position.x = mu_t[0, 0]    
    pose.position.y = mu_t[1, 0] 
    pose.position.z = mu_t[2, 0]   #theta 

    x, y, z, w = angle2quarter(0, 0, mu_t[2, 0])

    pose.orientation.x = x
    pose.orientation.y = y
    pose.orientation.z = z
    pose.orientation.w = w

    model_state.pose = pose

    # twist
    linear = args[1].twist.twist.linear.x

    model_state.twist.linear.x = linear * cos(mu_t[2, 0])
    model_state.twist.linear.y = linear * sin(mu_t[2, 0]) 
    model_state.twist.angular = args[1].twist.twist.angular

    model_state.reference_frame = "global"

    mut_1 = mu_t
    sigmat_1 = sigma_t
    # robot_state_msg
    robot_state_msg.modelstate = model_state

    pub_robot_state.publish(robot_state_msg)

    # print("robot2trans: publish robot information messages successfully")

def robot_state_publish():
    
    rospy.init_node('robot2trans', anonymous=True)
    rate=rospy.Rate(50)
    # should input the robot name from commond line
    global robot_name 

    if (len(sys.argv)<2):
        print("no input, using the default robot name: agent1")
    else:
        robot_name = sys.argv[1]
            
    topic_name_odom = "/" + robot_name+"/odom"
    topic_name_uwb =  "/" + robot_name+"/nlink_linktrack_nodeframe2"   
    list_info_sub.append(message_filters.Subscriber(topic_name_uwb, node_frame2))
    list_info_sub.append(message_filters.Subscriber(topic_name_odom, Odometry))

    ts_info = message_filters.ApproximateTimeSynchronizer(list_info_sub, 10, 1)
    ts_info.registerCallback(robot_msg_callback)

    print("Configure successfully, waiting for odom and uwb message")

    rospy.spin()

    while not rospy.is_shutdown():
        rate.sleep()
        
if __name__=='__main__':
    try:
        robot_state_publish()
    except rospy.ROSInterruptException:
        pass



